pipeline {
    agent any

    environment {
        AWS_REGION = 'eu-north-1'
        ECR_REPO = 'inventory-backend'
        ECR_URI = '485734076576.dkr.ecr.eu-north-1.amazonaws.com/inventory-backend'
        IMAGE_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'git@github.com:shubhchaudhari7901/Inventory-Stock-Management.git'
            }
        }

       stage('Build JAR') {
    steps {
        dir('backend') {
            sh 'mvn clean package -DskipTests'
        }
    }
}


        stage('Build Docker Image') {
    steps {
        dir('backend') {
            script {
                sh "docker build -t ${ECR_REPO}:${IMAGE_TAG} ."
            }
        }
    }
}


        stage('Login to ECR') {
            steps {
                withAWS(credentials: 'aws-creds', region: "${AWS_REGION}") {
                    script {
                        sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_URI}"
                    }
                }
            }
        }

        stage('Tag & Push Docker Image') {
            steps {
                script {
                    sh """
                        docker tag ${ECR_REPO}:${IMAGE_TAG} ${ECR_URI}:${IMAGE_TAG}
                        docker push ${ECR_URI}:${IMAGE_TAG}
                    """
                }
            }
        }
    }

    post {
        success {
            echo '✅ Docker image pushed successfully to ECR!'
        }
        failure {
            echo '❌ Build or push failed.'
        }
    }
}
